server.port=80
server.error.include-stacktrace=never

#configuración MySQL hosting
spring.datasource.url=jdbc:mysql://URL
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# Inicialización de la base de datos  data.sql (cambiar cuando este definitivo)
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always 
spring.jpa.defer-datasource-initialization=true

#spring.jpa.hibernate.ddl-auto=validate
#spring.sql.init.mode=never

# Allowed origin for WebSocket (production)
app.websocket.allowed-origin=

app.frontend.url=https://tuservidor.com