server.port=9000
server.error.include-stacktrace=always

#configuración H2
spring.datasource.url=jdbc:h2:file:./dbfiles/cryptum
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Force SQL initialization and defer it until after Hibernate creates the schema
# Ensures that `data.sql` is executed after JPA/Hibernate has created the tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.frontend.url=http://localhost:5173/

# Allowed origin for WebSocket (production)
app.websocket.allowed-origin=http://localhost:5173