spring.application.name=Cryptum
spring.thymeleaf.cache=false
spring.web.error.include-message=always
#el perfil se establece en Dockerfile a "prod" sobreescribiendo el siguiente valor
spring.profiles.active=dev